// Country data with ISO codes, names, flags, and continent groupings
// Used by the CountrySelect component in campaign creation

export const CONTINENTS = {
    EUROPE: {
        label: 'Europe',
        emoji: '🌍',
        color: 'text-blue-400',
        bg: 'bg-blue-500/10',
        border: 'border-blue-500/30',
    },
    NORTH_AMERICA: {
        label: 'North America',
        emoji: '🌎',
        color: 'text-green-400',
        bg: 'bg-green-500/10',
        border: 'border-green-500/30',
    },
    SOUTH_AMERICA: {
        label: 'South America',
        emoji: '🌎',
        color: 'text-yellow-400',
        bg: 'bg-yellow-500/10',
        border: 'border-yellow-500/30',
    },
    ASIA: {
        label: 'Asia',
        emoji: '🌏',
        color: 'text-orange-400',
        bg: 'bg-orange-500/10',
        border: 'border-orange-500/30',
    },
    MIDDLE_EAST: {
        label: 'Middle East',
        emoji: '🌏',
        color: 'text-amber-400',
        bg: 'bg-amber-500/10',
        border: 'border-amber-500/30',
    },
    AFRICA: {
        label: 'Africa',
        emoji: '🌍',
        color: 'text-red-400',
        bg: 'bg-red-500/10',
        border: 'border-red-500/30',
    },
    OCEANIA: {
        label: 'Oceania',
        emoji: '🌏',
        color: 'text-teal-400',
        bg: 'bg-teal-500/10',
        border: 'border-teal-500/30',
    },
};

export const COUNTRIES = [
    // ===== EUROPE =====
    { code: 'AL', name: 'Albania', flag: '🇦🇱', continent: 'EUROPE' },
    { code: 'AD', name: 'Andorra', flag: '🇦🇩', continent: 'EUROPE' },
    { code: 'AT', name: 'Austria', flag: '🇦🇹', continent: 'EUROPE' },
    { code: 'BY', name: 'Belarus', flag: '🇧🇾', continent: 'EUROPE' },
    { code: 'BE', name: 'Belgium', flag: '🇧🇪', continent: 'EUROPE' },
    { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', continent: 'EUROPE' },
    { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', continent: 'EUROPE' },
    { code: 'HR', name: 'Croatia', flag: '🇭🇷', continent: 'EUROPE' },
    { code: 'CY', name: 'Cyprus', flag: '🇨🇾', continent: 'EUROPE' },
    { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', continent: 'EUROPE' },
    { code: 'DK', name: 'Denmark', flag: '🇩🇰', continent: 'EUROPE' },
    { code: 'EE', name: 'Estonia', flag: '🇪🇪', continent: 'EUROPE' },
    { code: 'FI', name: 'Finland', flag: '🇫🇮', continent: 'EUROPE' },
    { code: 'FR', name: 'France', flag: '🇫🇷', continent: 'EUROPE' },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', continent: 'EUROPE' },
    { code: 'GR', name: 'Greece', flag: '🇬🇷', continent: 'EUROPE' },
    { code: 'HU', name: 'Hungary', flag: '🇭🇺', continent: 'EUROPE' },
    { code: 'IS', name: 'Iceland', flag: '🇮🇸', continent: 'EUROPE' },
    { code: 'IE', name: 'Ireland', flag: '🇮🇪', continent: 'EUROPE' },
    { code: 'IT', name: 'Italy', flag: '🇮🇹', continent: 'EUROPE' },
    { code: 'XK', name: 'Kosovo', flag: '🇽🇰', continent: 'EUROPE' },
    { code: 'LV', name: 'Latvia', flag: '🇱🇻', continent: 'EUROPE' },
    { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', continent: 'EUROPE' },
    { code: 'LT', name: 'Lithuania', flag: '🇱🇹', continent: 'EUROPE' },
    { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', continent: 'EUROPE' },
    { code: 'MT', name: 'Malta', flag: '🇲🇹', continent: 'EUROPE' },
    { code: 'MD', name: 'Moldova', flag: '🇲🇩', continent: 'EUROPE' },
    { code: 'MC', name: 'Monaco', flag: '🇲🇨', continent: 'EUROPE' },
    { code: 'ME', name: 'Montenegro', flag: '🇲🇪', continent: 'EUROPE' },
    { code: 'NL', name: 'Netherlands', flag: '🇳🇱', continent: 'EUROPE' },
    { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', continent: 'EUROPE' },
    { code: 'NO', name: 'Norway', flag: '🇳🇴', continent: 'EUROPE' },
    { code: 'PL', name: 'Poland', flag: '🇵🇱', continent: 'EUROPE' },
    { code: 'PT', name: 'Portugal', flag: '🇵🇹', continent: 'EUROPE' },
    { code: 'RO', name: 'Romania', flag: '🇷🇴', continent: 'EUROPE' },
    { code: 'RU', name: 'Russia', flag: '🇷🇺', continent: 'EUROPE' },
    { code: 'SM', name: 'San Marino', flag: '🇸🇲', continent: 'EUROPE' },
    { code: 'RS', name: 'Serbia', flag: '🇷🇸', continent: 'EUROPE' },
    { code: 'SK', name: 'Slovakia', flag: '🇸🇰', continent: 'EUROPE' },
    { code: 'SI', name: 'Slovenia', flag: '🇸🇮', continent: 'EUROPE' },
    { code: 'ES', name: 'Spain', flag: '🇪🇸', continent: 'EUROPE' },
    { code: 'SE', name: 'Sweden', flag: '🇸🇪', continent: 'EUROPE' },
    { code: 'CH', name: 'Switzerland', flag: '🇨🇭', continent: 'EUROPE' },
    { code: 'UA', name: 'Ukraine', flag: '🇺🇦', continent: 'EUROPE' },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', continent: 'EUROPE' },
    { code: 'VA', name: 'Vatican City', flag: '🇻🇦', continent: 'EUROPE' },

    // ===== NORTH AMERICA =====
    { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', continent: 'NORTH_AMERICA' },
    { code: 'BS', name: 'Bahamas', flag: '🇧🇸', continent: 'NORTH_AMERICA' },
    { code: 'BB', name: 'Barbados', flag: '🇧🇧', continent: 'NORTH_AMERICA' },
    { code: 'BZ', name: 'Belize', flag: '🇧🇿', continent: 'NORTH_AMERICA' },
    { code: 'CA', name: 'Canada', flag: '🇨🇦', continent: 'NORTH_AMERICA' },
    { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', continent: 'NORTH_AMERICA' },
    { code: 'CU', name: 'Cuba', flag: '🇨🇺', continent: 'NORTH_AMERICA' },
    { code: 'DM', name: 'Dominica', flag: '🇩🇲', continent: 'NORTH_AMERICA' },
    { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', continent: 'NORTH_AMERICA' },
    { code: 'SV', name: 'El Salvador', flag: '🇸🇻', continent: 'NORTH_AMERICA' },
    { code: 'GD', name: 'Grenada', flag: '🇬🇩', continent: 'NORTH_AMERICA' },
    { code: 'GT', name: 'Guatemala', flag: '🇬🇹', continent: 'NORTH_AMERICA' },
    { code: 'HT', name: 'Haiti', flag: '🇭🇹', continent: 'NORTH_AMERICA' },
    { code: 'HN', name: 'Honduras', flag: '🇭🇳', continent: 'NORTH_AMERICA' },
    { code: 'JM', name: 'Jamaica', flag: '🇯🇲', continent: 'NORTH_AMERICA' },
    { code: 'MX', name: 'Mexico', flag: '🇲🇽', continent: 'NORTH_AMERICA' },
    { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', continent: 'NORTH_AMERICA' },
    { code: 'PA', name: 'Panama', flag: '🇵🇦', continent: 'NORTH_AMERICA' },
    { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', continent: 'NORTH_AMERICA' },
    { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', continent: 'NORTH_AMERICA' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', continent: 'NORTH_AMERICA' },
    { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', continent: 'NORTH_AMERICA' },
    { code: 'US', name: 'United States', flag: '🇺🇸', continent: 'NORTH_AMERICA' },

    // ===== SOUTH AMERICA =====
    { code: 'AR', name: 'Argentina', flag: '🇦🇷', continent: 'SOUTH_AMERICA' },
    { code: 'BO', name: 'Bolivia', flag: '🇧🇴', continent: 'SOUTH_AMERICA' },
    { code: 'BR', name: 'Brazil', flag: '🇧🇷', continent: 'SOUTH_AMERICA' },
    { code: 'CL', name: 'Chile', flag: '🇨🇱', continent: 'SOUTH_AMERICA' },
    { code: 'CO', name: 'Colombia', flag: '🇨🇴', continent: 'SOUTH_AMERICA' },
    { code: 'EC', name: 'Ecuador', flag: '🇪🇨', continent: 'SOUTH_AMERICA' },
    { code: 'GY', name: 'Guyana', flag: '🇬🇾', continent: 'SOUTH_AMERICA' },
    { code: 'PY', name: 'Paraguay', flag: '🇵🇾', continent: 'SOUTH_AMERICA' },
    { code: 'PE', name: 'Peru', flag: '🇵🇪', continent: 'SOUTH_AMERICA' },
    { code: 'SR', name: 'Suriname', flag: '🇸🇷', continent: 'SOUTH_AMERICA' },
    { code: 'UY', name: 'Uruguay', flag: '🇺🇾', continent: 'SOUTH_AMERICA' },
    { code: 'VE', name: 'Venezuela', flag: '🇻🇪', continent: 'SOUTH_AMERICA' },

    // ===== ASIA =====
    { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', continent: 'ASIA' },
    { code: 'AM', name: 'Armenia', flag: '🇦🇲', continent: 'ASIA' },
    { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', continent: 'ASIA' },
    { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', continent: 'ASIA' },
    { code: 'BT', name: 'Bhutan', flag: '🇧🇹', continent: 'ASIA' },
    { code: 'BN', name: 'Brunei', flag: '🇧🇳', continent: 'ASIA' },
    { code: 'KH', name: 'Cambodia', flag: '🇰🇭', continent: 'ASIA' },
    { code: 'CN', name: 'China', flag: '🇨🇳', continent: 'ASIA' },
    { code: 'GE', name: 'Georgia', flag: '🇬🇪', continent: 'ASIA' },
    { code: 'IN', name: 'India', flag: '🇮🇳', continent: 'ASIA' },
    { code: 'ID', name: 'Indonesia', flag: '🇮🇩', continent: 'ASIA' },
    { code: 'JP', name: 'Japan', flag: '🇯🇵', continent: 'ASIA' },
    { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', continent: 'ASIA' },
    { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', continent: 'ASIA' },
    { code: 'LA', name: 'Laos', flag: '🇱🇦', continent: 'ASIA' },
    { code: 'MY', name: 'Malaysia', flag: '🇲🇾', continent: 'ASIA' },
    { code: 'MV', name: 'Maldives', flag: '🇲🇻', continent: 'ASIA' },
    { code: 'MN', name: 'Mongolia', flag: '🇲🇳', continent: 'ASIA' },
    { code: 'MM', name: 'Myanmar', flag: '🇲🇲', continent: 'ASIA' },
    { code: 'NP', name: 'Nepal', flag: '🇳🇵', continent: 'ASIA' },
    { code: 'KP', name: 'North Korea', flag: '🇰🇵', continent: 'ASIA' },
    { code: 'PK', name: 'Pakistan', flag: '🇵🇰', continent: 'ASIA' },
    { code: 'PH', name: 'Philippines', flag: '🇵🇭', continent: 'ASIA' },
    { code: 'SG', name: 'Singapore', flag: '🇸🇬', continent: 'ASIA' },
    { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', continent: 'ASIA' },
    { code: 'KR', name: 'South Korea', flag: '🇰🇷', continent: 'ASIA' },
    { code: 'TW', name: 'Taiwan', flag: '🇹🇼', continent: 'ASIA' },
    { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', continent: 'ASIA' },
    { code: 'TH', name: 'Thailand', flag: '🇹🇭', continent: 'ASIA' },
    { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', continent: 'ASIA' },
    { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', continent: 'ASIA' },
    { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', continent: 'ASIA' },
    { code: 'VN', name: 'Vietnam', flag: '🇻🇳', continent: 'ASIA' },

    // ===== MIDDLE EAST =====
    { code: 'BH', name: 'Bahrain', flag: '🇧🇭', continent: 'MIDDLE_EAST' },
    { code: 'EG', name: 'Egypt', flag: '🇪🇬', continent: 'MIDDLE_EAST' },
    { code: 'IR', name: 'Iran', flag: '🇮🇷', continent: 'MIDDLE_EAST' },
    { code: 'IQ', name: 'Iraq', flag: '🇮🇶', continent: 'MIDDLE_EAST' },
    { code: 'IL', name: 'Israel', flag: '🇮🇱', continent: 'MIDDLE_EAST' },
    { code: 'JO', name: 'Jordan', flag: '🇯🇴', continent: 'MIDDLE_EAST' },
    { code: 'KW', name: 'Kuwait', flag: '🇰🇼', continent: 'MIDDLE_EAST' },
    { code: 'LB', name: 'Lebanon', flag: '🇱🇧', continent: 'MIDDLE_EAST' },
    { code: 'OM', name: 'Oman', flag: '🇴🇲', continent: 'MIDDLE_EAST' },
    { code: 'PS', name: 'Palestine', flag: '🇵🇸', continent: 'MIDDLE_EAST' },
    { code: 'QA', name: 'Qatar', flag: '🇶🇦', continent: 'MIDDLE_EAST' },
    { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', continent: 'MIDDLE_EAST' },
    { code: 'SY', name: 'Syria', flag: '🇸🇾', continent: 'MIDDLE_EAST' },
    { code: 'TR', name: 'Turkey', flag: '🇹🇷', continent: 'MIDDLE_EAST' },
    { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', continent: 'MIDDLE_EAST' },
    { code: 'YE', name: 'Yemen', flag: '🇾🇪', continent: 'MIDDLE_EAST' },

    // ===== AFRICA =====
    { code: 'DZ', name: 'Algeria', flag: '🇩🇿', continent: 'AFRICA' },
    { code: 'AO', name: 'Angola', flag: '🇦🇴', continent: 'AFRICA' },
    { code: 'BJ', name: 'Benin', flag: '🇧🇯', continent: 'AFRICA' },
    { code: 'BW', name: 'Botswana', flag: '🇧🇼', continent: 'AFRICA' },
    { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', continent: 'AFRICA' },
    { code: 'BI', name: 'Burundi', flag: '🇧🇮', continent: 'AFRICA' },
    { code: 'CV', name: 'Cape Verde', flag: '🇨🇻', continent: 'AFRICA' },
    { code: 'CM', name: 'Cameroon', flag: '🇨🇲', continent: 'AFRICA' },
    { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', continent: 'AFRICA' },
    { code: 'TD', name: 'Chad', flag: '🇹🇩', continent: 'AFRICA' },
    { code: 'KM', name: 'Comoros', flag: '🇰🇲', continent: 'AFRICA' },
    { code: 'CG', name: 'Congo', flag: '🇨🇬', continent: 'AFRICA' },
    { code: 'CD', name: 'DR Congo', flag: '🇨🇩', continent: 'AFRICA' },
    { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', continent: 'AFRICA' },
    { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', continent: 'AFRICA' },
    { code: 'ER', name: 'Eritrea', flag: '🇪🇷', continent: 'AFRICA' },
    { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', continent: 'AFRICA' },
    { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', continent: 'AFRICA' },
    { code: 'GA', name: 'Gabon', flag: '🇬🇦', continent: 'AFRICA' },
    { code: 'GM', name: 'Gambia', flag: '🇬🇲', continent: 'AFRICA' },
    { code: 'GH', name: 'Ghana', flag: '🇬🇭', continent: 'AFRICA' },
    { code: 'GN', name: 'Guinea', flag: '🇬🇳', continent: 'AFRICA' },
    { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', continent: 'AFRICA' },
    { code: 'CI', name: "Ivory Coast", flag: '🇨🇮', continent: 'AFRICA' },
    { code: 'KE', name: 'Kenya', flag: '🇰🇪', continent: 'AFRICA' },
    { code: 'LS', name: 'Lesotho', flag: '🇱🇸', continent: 'AFRICA' },
    { code: 'LR', name: 'Liberia', flag: '🇱🇷', continent: 'AFRICA' },
    { code: 'LY', name: 'Libya', flag: '🇱🇾', continent: 'AFRICA' },
    { code: 'MG', name: 'Madagascar', flag: '🇲🇬', continent: 'AFRICA' },
    { code: 'MW', name: 'Malawi', flag: '🇲🇼', continent: 'AFRICA' },
    { code: 'ML', name: 'Mali', flag: '🇲🇱', continent: 'AFRICA' },
    { code: 'MR', name: 'Mauritania', flag: '🇲🇷', continent: 'AFRICA' },
    { code: 'MU', name: 'Mauritius', flag: '🇲🇺', continent: 'AFRICA' },
    { code: 'MA', name: 'Morocco', flag: '🇲🇦', continent: 'AFRICA' },
    { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', continent: 'AFRICA' },
    { code: 'NA', name: 'Namibia', flag: '🇳🇦', continent: 'AFRICA' },
    { code: 'NE', name: 'Niger', flag: '🇳🇪', continent: 'AFRICA' },
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬', continent: 'AFRICA' },
    { code: 'RW', name: 'Rwanda', flag: '🇷🇼', continent: 'AFRICA' },
    { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', continent: 'AFRICA' },
    { code: 'SN', name: 'Senegal', flag: '🇸🇳', continent: 'AFRICA' },
    { code: 'SC', name: 'Seychelles', flag: '🇸🇨', continent: 'AFRICA' },
    { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', continent: 'AFRICA' },
    { code: 'SO', name: 'Somalia', flag: '🇸🇴', continent: 'AFRICA' },
    { code: 'ZA', name: 'South Africa', flag: '🇿🇦', continent: 'AFRICA' },
    { code: 'SS', name: 'South Sudan', flag: '🇸🇸', continent: 'AFRICA' },
    { code: 'SD', name: 'Sudan', flag: '🇸🇩', continent: 'AFRICA' },
    { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', continent: 'AFRICA' },
    { code: 'TG', name: 'Togo', flag: '🇹🇬', continent: 'AFRICA' },
    { code: 'TN', name: 'Tunisia', flag: '🇹🇳', continent: 'AFRICA' },
    { code: 'UG', name: 'Uganda', flag: '🇺🇬', continent: 'AFRICA' },
    { code: 'ZM', name: 'Zambia', flag: '🇿🇲', continent: 'AFRICA' },
    { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', continent: 'AFRICA' },

    // ===== OCEANIA =====
    { code: 'AU', name: 'Australia', flag: '🇦🇺', continent: 'OCEANIA' },
    { code: 'FJ', name: 'Fiji', flag: '🇫🇯', continent: 'OCEANIA' },
    { code: 'KI', name: 'Kiribati', flag: '🇰🇮', continent: 'OCEANIA' },
    { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', continent: 'OCEANIA' },
    { code: 'FM', name: 'Micronesia', flag: '🇫🇲', continent: 'OCEANIA' },
    { code: 'NR', name: 'Nauru', flag: '🇳🇷', continent: 'OCEANIA' },
    { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', continent: 'OCEANIA' },
    { code: 'PW', name: 'Palau', flag: '🇵🇼', continent: 'OCEANIA' },
    { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', continent: 'OCEANIA' },
    { code: 'WS', name: 'Samoa', flag: '🇼🇸', continent: 'OCEANIA' },
    { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', continent: 'OCEANIA' },
    { code: 'TO', name: 'Tonga', flag: '🇹🇴', continent: 'OCEANIA' },
    { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', continent: 'OCEANIA' },
    { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', continent: 'OCEANIA' },
];

// Helper: tüm ülkeleri kıtaya göre grupla
export const getCountriesByContinent = () => {
    const groups = {};
    for (const continent of Object.keys(CONTINENTS)) {
        groups[continent] = COUNTRIES.filter(c => c.continent === continent);
    }
    return groups;
};

// Helper: kıtadaki tüm kodları döndür
export const getCountryCodesByContinent = (continentKey) => {
    return COUNTRIES.filter(c => c.continent === continentKey).map(c => c.code);
};

// Helper: ülke kodundan ülke bilgisi
export const getCountryByCode = (code) => {
    return COUNTRIES.find(c => c.code === code);
};
